// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWQ5_kG1NjzxeqTko-O6lFjQ35Y99bWIc',
    appId: '1:896825931400:android:16d4e4b16f37a695d8513d',
    messagingSenderId: '896825931400',
    projectId: 'ittierra-project',
    storageBucket: 'ittierra-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ9hklvA77O1xa-qOwvdU5CDCKvMie-hw',
    appId: '1:896825931400:ios:91613914c7f0214fd8513d',
    messagingSenderId: '896825931400',
    projectId: 'ittierra-project',
    storageBucket: 'ittierra-project.appspot.com',
    iosClientId: '896825931400-rgt93dn2rs022q0dp1c2dg8mnae9bevd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ittierraApp',
  );
}
